USE zhuhai_travel;

ALTER TABLE audit_logs
  ADD COLUMN IF NOT EXISTS actor_name VARCHAR(120) NULL AFTER actor_id,
  ADD COLUMN IF NOT EXISTS method VARCHAR(12) NOT NULL DEFAULT '' AFTER target_id,
  ADD COLUMN IF NOT EXISTS path VARCHAR(255) NOT NULL DEFAULT '' AFTER method,
  ADD COLUMN IF NOT EXISTS status_code INT NOT NULL DEFAULT 0 AFTER path;
